
// import './global.css'
import type { Metadata } from "next"

import { ChakraProvider } from "@chakra-ui/react"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
// const styles = StyleSheet.create{
//   background {
//     background: rgb(251, 237, 255);
// backgroundRadialGradient(circle, rgba(251, 237, 255, 1) 0 %, rgba(255, 255, 255, 1) 36 %);
// }

// tasklist {
//   title: {
//     backgroundImage: {
//       linearGradient:(45deg, #ff8a00, #e52e71);
//     }
//     webkitBackgroundClip: 'text'
//   };
//   backgroundClip: 'initial';
//   color: 'transparent';
// }

// tasklist - slogan: {

//   color: #333333;
// }
// }